name: Event Pull Request
on:
  push:
    branches: [main, 'dev-*', 'feat/**']
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output event data
        run: echo "${{toJSON(github.event)}}"
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencias
        run: npm ci
      - name: Test code
        run: npm run test
